//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPIS.BL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public string Item { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ImageUrl { get; set; }
        public string ImageName { get; set; }
        public string ThumbNailUrl { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifedOn { get; set; }
        public Nullable<System.DateTime> ModifiedBy { get; set; }
    }
}
