//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPIS.BL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoggedUserInfo
    {
        public int Id { get; set; }
        public string ActiveUser { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
    }
}
